### PR TITLE
Option to create release with generated IaC

### PR DESCRIPTION
**Pull request by PhillypHenning**
## README.md
This diff adds a new input option for `create_release` and a default value for `aws_ami_id` to the list of input options for jobs. It also adds default values for some existing input options, as well as clarifying descriptions for the existing options.

## action.yaml
This diff adds two new inputs to the action.yaml file, creates a new release by compressing the resulting terraform and ansible files and then creates a GitHub release with the generated release.zip artifact. The release will be a draft and will have the same name as the branch.

### CODE REVIEW

**Comment by PhillypHenning** [comment]
Screen Shot 2023-01-27 at 11 20 43 AM
Screen Shot 2023-01-27 at 11 20 40 AM

**Comment by mickmcgrath13** [comment]
What's this aiming to solve?

**Comment by PhillypHenning** [comment]
This provides a snapshot of the infra generated. 
That could potentially be helpful in the case of emergency issues as it gives users the ability to pull out the terraform generated to manage it more manually. 

I personally see this being handy if resources are accidentally deleted in the console resulting in a broken state file.

**Comment by PhillypHenning** [comment]
@armab I think your suggestion to use https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts might be more appropriate. 👍

**Comment by PhillypHenning** [comment]
Also keep in mind that the default behaviour is to NOT create the release. It must be toggled `on` by the user so there wouldn't actually be releases being created "per PR environment" unless that was intended.

**Comment by PhillypHenning** [comment]
That said, I think @armab may be correct that we should be creating an artifact which will be associated to the workflow instead of creating a draft release.

**Comment by LeoDiazL** [comment]
Done in GHA commons, will be an option after we migrate this to commons.

**Pull request closed without merging**
